name: "push to ghcr"

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.17
      - uses: imjasonh/setup-ko@v0.4
      - run: |
          ko publish --bare --platform=linux/amd64,linux/arm64 \
          --tags=latest,$(git describe --tag --always --dirty) ./
